// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { MainGetData, MainGetResponses, ProcessTranscriptApiV1TranscriptPostData, ProcessTranscriptApiV1TranscriptPostErrors, ProcessTranscriptApiV1TranscriptPostResponses, ReadRootHealthGetData, ReadRootHealthGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Process Transcript
 */
export const processTranscriptApiV1TranscriptPost = <ThrowOnError extends boolean = false>(options?: Options<ProcessTranscriptApiV1TranscriptPostData, ThrowOnError>) => (options?.client ?? client).post<ProcessTranscriptApiV1TranscriptPostResponses, ProcessTranscriptApiV1TranscriptPostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/v1/transcript',
    ...options,
    headers: {
        'Content-Type': null,
        ...options?.headers
    }
});

/**
 * Main
 */
export const mainGet = <ThrowOnError extends boolean = false>(options?: Options<MainGetData, ThrowOnError>) => (options?.client ?? client).get<MainGetResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Read Root
 */
export const readRootHealthGet = <ThrowOnError extends boolean = false>(options?: Options<ReadRootHealthGetData, ThrowOnError>) => (options?.client ?? client).get<ReadRootHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });
