// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_process_transcript_api_v1_transcript_post
 */
export type BodyProcessTranscriptApiV1TranscriptPost = {
    /**
     * Text
     */
    text?: string | null;
    /**
     * File
     */
    file?: Blob | File | null;
};

/**
 * Email
 */
export type Email = {
    /**
     * To
     *
     * Comma separated email recipients i.e. "James Robinson <james@gmail.com>, Reuben Hayden <reuben@gmail.com>". If email, just put the name, if both email and name is unknown please input title of intended recipient.
     */
    to: string;
    /**
     * Cc
     *
     * Comma separated CC email recipients i.e. "James Robinson <james@gmail.com>, Reuben Hayden <reuben@gmail.com>". If email, just put the name, if both email and name is unknown please input title of intended recipient.
     */
    cc?: string | null;
    /**
     * Bcc
     *
     * Comma separated BCC email recipients i.e. "James Robinson <james@gmail.com>, Reuben Hayden <reuben@gmail.com>". If email, just put the name, if both email and name is unknown please input title of intended recipient.
     */
    bcc?: string | null;
    /**
     * Subject
     *
     * Subject line of email.
     */
    subject: string;
    /**
     * Body
     *
     * Body of email, please use markdown.
     */
    body: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IncidentReport
 */
export type IncidentReport = {
    /**
     * Date Time Of Incident
     *
     * Date and time when the incident occurred in ISO 8601 format (YYYY-MM-DDTHH:MM:SS)
     */
    date_time_of_incident?: string | null;
    /**
     * Service User Name
     *
     * Full name of the service user involved in the incident
     */
    service_user_name: string;
    /**
     * Location Of Incident
     *
     * Specific location where the incident took place
     */
    location_of_incident?: string | null;
    /**
     * Type Of Incident
     *
     * Category of incident (e.g., Fall, Medical Emergency, Behavioral, etc.)
     */
    type_of_incident: string;
    /**
     * Description Of Incident
     *
     * Detailed description of what happened during the incident
     */
    description_of_incident: string;
    /**
     * Immediate Actions Taken
     *
     * Actions taken immediately following the incident
     */
    immediate_actions_taken?: string | null;
    /**
     * First Aid Administered
     *
     * Whether first aid was provided
     */
    first_aid_administered: boolean;
    /**
     * Emergency Services Contacted
     *
     * Whether emergency services (ambulance, police, fire) were called
     */
    emergency_services_contacted: boolean;
    /**
     * Who Was Notified
     *
     * Names and roles of people notified about the incident
     */
    who_was_notified?: string | null;
    /**
     * Witnesses
     *
     * Names of any witnesses to the incident
     */
    witnesses?: string | null;
    /**
     * Agreed Next Steps
     *
     * Follow-up actions agreed upon after the incident
     */
    agreed_next_steps?: string | null;
    /**
     * Risk Assessment Needed
     *
     * Whether a risk assessment is required
     */
    risk_assessment_needed: boolean;
    /**
     * Risk Assessment Type
     *
     * Type of risk assessment needed (e.g., Moving and Handling, Environmental)
     */
    risk_assessment_type?: string | null;
};

/**
 * PolicyProcessingResultsWithFullPolicy
 */
export type PolicyProcessingResultsWithFullPolicy = {
    /**
     * Emails
     */
    emails: Array<Email>;
    report: IncidentReport;
    /**
     * Policy Ids
     *
     * The IDs of the returned situations you used to fill out the incident report as well as draft emails.
     */
    policy_ids: Array<string>;
    /**
     * Reasoning
     *
     * A list of reasons why the outputs are in line with policy, specifically which parts of the text are related to specificaly parts of the policy. Please use quotations and please use markdown
     */
    reasoning: Array<string>;
    /**
     * Full Policy Texts
     */
    full_policy_texts: Array<string>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ProcessTranscriptApiV1TranscriptPostData = {
    body?: BodyProcessTranscriptApiV1TranscriptPost;
    path?: never;
    query?: never;
    url: '/api/v1/transcript';
};

export type ProcessTranscriptApiV1TranscriptPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProcessTranscriptApiV1TranscriptPostError = ProcessTranscriptApiV1TranscriptPostErrors[keyof ProcessTranscriptApiV1TranscriptPostErrors];

export type ProcessTranscriptApiV1TranscriptPostResponses = {
    /**
     * Successful Response
     */
    200: PolicyProcessingResultsWithFullPolicy;
};

export type ProcessTranscriptApiV1TranscriptPostResponse = ProcessTranscriptApiV1TranscriptPostResponses[keyof ProcessTranscriptApiV1TranscriptPostResponses];

export type MainGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type MainGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadRootHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type ReadRootHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
